<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="shortcut icon" href="pluton.ico" />
<title>Pluton ethernet controller</title>
<link href="mchp.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px">
	<img  width="100" src="pluton_logo1.gif" alt="Microchip" />
	<img  style="float: right;" height="100" src="pluton_logo43.png" alt="Microchip" />
</div>

<div id="title"><div class="right">Pluton ethernet controller</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="index.htm">Сеть</a>
<a href="server.htm">Уждаленный сервер</a>
<a href="sequrity.htm">Безопасность</a>
</div>
~inc:header.inc~